# Generated by Django 4.0.5 on 2022-06-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('inn_code', models.IntegerField(unique=True, verbose_name='ИНН')),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('telephone', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='max_people',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ownership_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='region',
            field=models.CharField(choices=[('Бишкек', 'Бишкек'), ('Ош', 'Ош'), ('Баткен', 'Баткен'), ('Жалал-Абад', 'Жалал-Абад'), ('Нарын', 'Нарын'), ('Ошская обл.', 'Ошская обл.'), ('Талас', 'Талас'), ('Чуйская обл.', 'Чуйская обл.'), ('Ысык-Кол', 'Ысык-Кол')], default='Кыргызстан', max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='classification_code',
            field=models.IntegerField(unique=True, verbose_name='ОКПО'),
        ),
    ]
