# Generated by Django 4.0.5 on 2022-06-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='region',
            field=models.CharField(choices=[('Бишкек', 'Бишкек'), ('Ош', 'Ош'), ('Баткен', 'Баткен'), ('Жалал-Абад', 'Жалал-Абад'), ('Нарын', 'Нарын'), ('Ошская обл.', 'Ошская обл.'), ('Талас', 'Талас'), ('Чуйская обл.', 'Чуйская обл.'), ('Ысык-Кол', 'Ысык-Кол')], default='Бишкек', max_length=30),
        ),
    ]
