# Generated by Django 4.0.5 on 2022-06-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_headdoctor_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='head_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.headdoctor'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
    ]
