# Generated by Django 4.0.5 on 2022-06-21 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_headdoctor_hospital_max_people_hospital_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(choices=[('Хирург', 'Хирург'), ('Терапевт', 'Терапевт')], max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('inn_code', models.IntegerField(unique=True, verbose_name='ИНН')),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('telephone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('inn_code', models.IntegerField(unique=True, verbose_name='ИНН')),
                ('age', models.IntegerField()),
                ('telephone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('inn_code', models.IntegerField(unique=True, verbose_name='ИНН')),
                ('age', models.IntegerField()),
                ('telephone', models.CharField(max_length=30)),
                ('diagnose', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='max_people',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
